#!/bin/bash
pid=$BASHPID
url=$1
file="tmpfile.$pid"
#echo $file
curl -I $url 2>/dev/null > $file
redirect=`cat $file | grep "HTTP/1.1 302 Found"`
if [ -z "$redirect" ]
then
	size=`cat $file | egrep 'Content-Length' | awk '{print \$NF}'`
	echo $size
else
	newurl=`cat $file  | egrep Location: | awk '{print $NF}'`
	curl -I $newurl 2>/dev/null > $file
	size=`cat $file | egrep 'Content-Length' | awk '{print \$NF}'`
	echo $size
fi
rm -f $file
